- hosts: all
  become: no

  tasks:
  # - name: Install Docker CE
  #   shell: |
  #     curl -fsSL https://get.docker.com | bash
  # - name: Install OS packages
  #   package:
  #     name:
  #       - make
  #       - rsync
  #       - time
  #       - less
  #     state: latest



  - name: Copy files
    synchronize:
      src: "{{ playbook_dir }}/../"
      dest: /adb-scripter
      rsync_opts:
      - "--exclude=.history"

  - name: Build and start application
    shell: |
      cd /adb-scripter
      rm .arch
      if lscpu | grep armv6l &>/dev/null; then
        echo "ARCH=arm32v5/" > .arch
      fi
      make build
      make run-with-restart