- hosts: all
  become: no
  user: root

  tasks:
  # - name: Install Docker CE
  #   shell: |
  #     curl -fsSL https://get.docker.com | bash
  # - name: Install OS packages
  #   package:
  #     name:
  #       - make
  #       - rsync
  #       - time
  #       - less
  #       - udev
  #     state: latest



  - name: Copy files
    synchronize:
      src: "{{ playbook_dir }}/../"
      dest: /adb-scripter
      rsync_opts:
      - "--exclude=.history"

  - name: Build and start application
    shell: |
      cd /adb-scripter
      make IMAGE_NAME_ARCH=_arm32v6 build
      make IMAGE_NAME_ARCH=_arm32v6 run-with-restart